project: 
  type: website
  output-dir: docs
  resources:
    - .nojekyll
website:
  title: "Chidera Orizu's Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/Chidex019/Chidera-portfolio.git
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Chidera Orizu 2025"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/chidera-orizu-8b5662250/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "consulting project"
        file: projects/consulting.Rmd
    
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Chi squared project"
      style: "docked"
      background: light
      contents:
        - text: "Chi squared project"
          file: projects/MyChisquaredTest.Rmd
        - text: "---"
        
    
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: lumen # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



